// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// C_VMBrowser wrapper class

class C_VMBrowser : public CWnd
{
protected:
	DECLARE_DYNCREATE(C_VMBrowser)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1e9a88a2, 0x2968, 0x11d1, { 0x85, 0x1d, 0x0, 0xa0, 0xc9, 0x11, 0xe8, 0xb0 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void InitBrowser(LPDISPATCH* TheReposObject, LPDISPATCH* VCMHandle);
};
